default: &default
  adapter: postgresql
  encoding: UTF8
  template: template_base
  username: postgres
  password: postgres
  pool: 15

development:
  <<: *default
  database: bugmark_development

test:
  <<: *default
  database: bugmark_test

production:
  <<: *default
  database: bugmark_production
